<?php

namespace Database\Seeders;

use App\Models\ModelsPermission;
use Illuminate\Database\Seeder;

class PermisionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $permissions = [
            //RBAC
            [
                'name'        => 'RBAC',
                'guard_name'  => 'web',
                'module_name' => null,
                'details'     => 'MODULE',
                'type'        => null,
            ],
            [
                'name'        => 'Role',
                'guard_name'  => 'web',
                'module_name' => 'RBAC',
                'details'     => 'FEATURE',
                'type'        => null,
            ],
            [
                'name'        => 'User',
                'guard_name'  => 'web',
                'module_name' => 'RBAC',
                'details'     => 'FEATURE',
                'type'        => null,
            ],
            [
                'name'        => 'User_Access',
                'guard_name'  => 'web',
                'module_name' => 'RBAC',
                'details'     => 'FEATURE',
                'type'        => null,
            ],
            [
                'name'        => 'Add_Role',
                'guard_name'  => 'web',
                'module_name' => 'Role',
                'details'     => 'Add_Role',
                'type'        => 1,
            ],
            [
                'name'        => 'Delete_Role',
                'guard_name'  => 'web',
                'module_name' => 'Role',
                'details'     => 'Delete_Role',
                'type'        => 4,
            ],
            [
                'name'        => 'View_Role',
                'guard_name'  => 'web',
                'module_name' => 'Role',
                'details'     => 'View_Role',
                'type'        => 5,
            ],
            [
                'name'        => 'Add_User',
                'guard_name'  => 'web',
                'module_name' => 'User',
                'details'     => 'Add_User',
                'type'        => 1,
            ],
            [
                'name'        => 'Delete_User',
                'guard_name'  => 'web',
                'module_name' => 'User',
                'details'     => 'Delete_User',
                'type'        => 4,
            ],
            [
                'name'        => 'access_for_user',
                'guard_name'  => 'web',
                'module_name' => 'User_Access',
                'details'     => 'access_for_user',
                'type'        => 1,
            ],
            //Department
            [
                'name'        => 'Department',
                'guard_name'  => 'web',
                'module_name' => null,
                'details'     => 'MODULE',
                'type'        => null,
            ],
            [
                'name'        => 'Department_Add',
                'guard_name'  => 'web',
                'module_name' => 'Department',
                'details'     => 'FEATURE',
                'type'        => null,
            ],
            [
                'name'        => 'Department_List',
                'guard_name'  => 'web',
                'module_name' => 'Department',
                'details'     => 'FEATURE',
                'type'        => null,
            ],
            [
                'name'        => 'Edit_Department',
                'guard_name'  => 'web',
                'module_name' => 'Department_List',
                'details'     => 'Edit_Department',
                'type'        => 2,
            ],
            [
                'name'        => 'Status_Department',
                'guard_name'  => 'web',
                'module_name' => 'Department_List',
                'details'     => 'Status_Department',
                'type'        => 3,
            ],
            [
                'name'        => 'Delete_Department',
                'guard_name'  => 'web',
                'module_name' => 'Department_List',
                'details'     => 'Delete_Department',
                'type'        => 4,
            ],
            //Doctor
            [
                'name'        => 'Doctor',
                'guard_name'  => 'web',
                'module_name' => null,
                'details'     => 'MODULE',
                'type'        => null,
            ],
            [
                'name'        => 'Doctor_Add',
                'guard_name'  => 'web',
                'module_name' => 'Doctor',
                'details'     => 'FEATURE',
                'type'        => null,
            ],
            [
                'name'        => 'Doctor_List',
                'guard_name'  => 'web',
                'module_name' => 'Doctor',
                'details'     => 'FEATURE',
                'type'        => null,
            ],
            [
                'name'        => 'Edit_Doctor',
                'guard_name'  => 'web',
                'module_name' => 'Doctor_List',
                'details'     => 'Edit_Doctor',
                'type'        => 2,
            ],
            [
                'name'        => 'Status_Doctor',
                'guard_name'  => 'web',
                'module_name' => 'Doctor_List',
                'details'     => 'Status_Doctor',
                'type'        => 3,
            ],
            [
                'name'        => 'Delete_Doctor',
                'guard_name'  => 'web',
                'module_name' => 'Doctor_List',
                'details'     => 'Delete_Doctor',
                'type'        => 4,
            ],
            [
                'name'        => 'View_Doctor',
                'guard_name'  => 'web',
                'module_name' => 'Doctor_List',
                'details'     => 'View_Doctor',
                'type'        => 5,
            ],
            //Patient
            [
                'name'        => 'Patient',
                'guard_name'  => 'web',
                'module_name' => null,
                'details'     => 'MODULE',
                'type'        => null,
            ],
            [
                'name'        => 'Patient_Add',
                'guard_name'  => 'web',
                'module_name' => 'Patient',
                'details'     => 'FEATURE',
                'type'        => null,
            ],
            [
                'name'        => 'Patient_List',
                'guard_name'  => 'web',
                'module_name' => 'Patient',
                'details'     => 'FEATURE',
                'type'        => null,
            ],
            [
                'name'        => 'Edit_Patient',
                'guard_name'  => 'web',
                'module_name' => 'Patient_List',
                'details'     => 'Edit_Patient',
                'type'        => 2,
            ],
            [
                'name'        => 'Status_Patient',
                'guard_name'  => 'web',
                'module_name' => 'Patient_List',
                'details'     => 'Status_Patient',
                'type'        => 3,
            ],
            [
                'name'        => 'Delete_Patient',
                'guard_name'  => 'web',
                'module_name' => 'Patient_List',
                'details'     => 'Delete_Patient',
                'type'        => 4,
            ],
            [
                'name'        => 'View_Patient',
                'guard_name'  => 'web',
                'module_name' => 'Patient_List',
                'details'     => 'View_Patient',
                'type'        => 5,
            ],
            //Schedule
            [
                'name'        => 'Schedule',
                'guard_name'  => 'web',
                'module_name' => null,
                'details'     => 'MODULE',
                'type'        => null,
            ],
            [
                'name'        => 'Schedule_Add',
                'guard_name'  => 'web',
                'module_name' => 'Schedule',
                'details'     => 'FEATURE',
                'type'        => null,
            ],
            [
                'name'        => 'Schedule_List',
                'guard_name'  => 'web',
                'module_name' => 'Schedule',
                'details'     => 'FEATURE',
                'type'        => null,
            ],
            [
                'name'        => 'Edit_Schedule',
                'guard_name'  => 'web',
                'module_name' => 'Schedule_List',
                'details'     => 'Edit_Schedule',
                'type'        => 2,
            ],
            [
                'name'        => 'Status_Schedule',
                'guard_name'  => 'web',
                'module_name' => 'Schedule_List',
                'details'     => 'Status_Schedule',
                'type'        => 3,
            ],
            [
                'name'        => 'Delete_Schedule',
                'guard_name'  => 'web',
                'module_name' => 'Schedule_List',
                'details'     => 'Delete_Schedule',
                'type'        => 4,
            ],
            //Appointments
            [
                'name'        => 'Appointment',
                'guard_name'  => 'web',
                'module_name' => null,
                'details'     => 'MODULE',
                'type'        => null,
            ],
            [
                'name'        => 'Appointment_list',
                'guard_name'  => 'web',
                'module_name' => 'Appointment',
                'details'     => 'FEATURE',
                'type'        => null,
            ],
            [
                'name'        => 'View_Appointment',
                'guard_name'  => 'web',
                'module_name' => 'Appointment_list',
                'details'     => 'View_Appointment',
                'type'        => 5,
            ],
            //Test
            [
                'name'        => 'Test',
                'guard_name'  => 'web',
                'module_name' => null,
                'details'     => 'MODULE',
                'type'        => null,
            ],
            [
                'name'        => 'Test_Type',
                'guard_name'  => 'web',
                'module_name' => 'Test',
                'details'     => 'FEATURE',
                'type'        => null,
            ],
            [
                'name'        => 'Test_Add',
                'guard_name'  => 'web',
                'module_name' => 'Test',
                'details'     => 'FEATURE',
                'type'        => null,
            ],
            [
                'name'        => 'Test_List',
                'guard_name'  => 'web',
                'module_name' => 'Test',
                'details'     => 'FEATURE',
                'type'        => null,
            ],
            [
                'name'        => 'Add_Test_Type',
                'guard_name'  => 'web',
                'module_name' => 'Test_Type',
                'details'     => 'Add_Test_Type',
                'type'        => 1,
            ],
            [
                'name'        => 'Edit_Test_Type',
                'guard_name'  => 'web',
                'module_name' => 'Test_Type',
                'details'     => 'Edit_Test_Type',
                'type'        => 2,
            ],
            [
                'name'        => 'Status_Test_Type',
                'guard_name'  => 'web',
                'module_name' => 'Test_Type',
                'details'     => 'Status_Test_Type',
                'type'        => 3,
            ],
            [
                'name'        => 'Delete_Test_Type',
                'guard_name'  => 'web',
                'module_name' => 'Test_Type',
                'details'     => 'Delete_Test_Type',
                'type'        => 4,
            ],
            [
                'name'        => 'Add_Test',
                'guard_name'  => 'web',
                'module_name' => 'Test_List',
                'details'     => 'Add_Test',
                'type'        => 1,
            ],
            [
                'name'        => 'Edit_Test',
                'guard_name'  => 'web',
                'module_name' => 'Test_List',
                'details'     => 'Edit_Test',
                'type'        => 2,
            ],
            [
                'name'        => 'Status_Test',
                'guard_name'  => 'web',
                'module_name' => 'Test_List',
                'details'     => 'Status_Test',
                'type'        => 3,
            ],
            [
                'name'        => 'Delete_Test',
                'guard_name'  => 'web',
                'module_name' => 'Test_List',
                'details'     => 'Delete_Test',
                'type'        => 4,
            ],
            [
                'name'        => 'View_Test',
                'guard_name'  => 'web',
                'module_name' => 'Test_List',
                'details'     => 'View_Test',
                'type'        => 5,
            ],

            //Medicine
            [
                'name'        => 'Medicine',
                'guard_name'  => 'web',
                'module_name' => null,
                'details'     => 'MODULE',
                'type'        => null,
            ],
            [
                'name'        => 'Medicine_Type',
                'guard_name'  => 'web',
                'module_name' => 'Medicine',
                'details'     => 'FEATURE',
                'type'        => null,
            ],
            [
                'name'        => 'Generic_List',
                'guard_name'  => 'web',
                'module_name' => 'Medicine',
                'details'     => 'FEATURE',
                'type'        => null,
            ],
            [
                'name'        => 'Manufacturer_List',
                'guard_name'  => 'web',
                'module_name' => 'Medicine',
                'details'     => 'FEATURE',
                'type'        => null,
            ],
            [
                'name'        => 'Add_Medicine',
                'guard_name'  => 'web',
                'module_name' => 'Medicine',
                'details'     => 'FEATURE',
                'type'        => null,
            ],
            [
                'name'        => 'Medicine_List',
                'guard_name'  => 'web',
                'module_name' => 'Medicine',
                'details'     => 'FEATURE',
                'type'        => null,
            ],

            [
                'name'        => 'Add_Medicine_Type',
                'guard_name'  => 'web',
                'module_name' => 'Medicine_Type',
                'details'     => 'Add_Medicine_Type',
                'type'        => 1,
            ],
            [
                'name'        => 'Edit_Medicine_Type',
                'guard_name'  => 'web',
                'module_name' => 'Medicine_Type',
                'details'     => 'Edit_Medicine_Type',
                'type'        => 2,
            ],
            [
                'name'        => 'Status_Medicine_Type',
                'guard_name'  => 'web',
                'module_name' => 'Medicine_Type',
                'details'     => 'Status_Medicine_Type',
                'type'        => 3,
            ],
            [
                'name'        => 'Delete_Medicine_Type',
                'guard_name'  => 'web',
                'module_name' => 'Medicine_Type',
                'details'     => 'Delete_Medicine_Type',
                'type'        => 4,
            ],
            [
                'name'        => 'Add_Generic',
                'guard_name'  => 'web',
                'module_name' => 'Generic_List',
                'details'     => 'Add_Generic',
                'type'        => 1,
            ],
            [
                'name'        => 'Edit_Generic',
                'guard_name'  => 'web',
                'module_name' => 'Generic_List',
                'details'     => 'Edit_Generic',
                'type'        => 2,
            ],
            [
                'name'        => 'Status_Generic',
                'guard_name'  => 'web',
                'module_name' => 'Generic_List',
                'details'     => 'Status_Generic',
                'type'        => 3,
            ],
            [
                'name'        => 'Delete_Generic',
                'guard_name'  => 'web',
                'module_name' => 'Generic_List',
                'details'     => 'Delete_Generic',
                'type'        => 4,
            ],
            [
                'name'        => 'View_Generic',
                'guard_name'  => 'web',
                'module_name' => 'Generic_List',
                'details'     => 'View_Generic',
                'type'        => 5,
            ],

            [
                'name'        => 'Add_Manufacturer',
                'guard_name'  => 'web',
                'module_name' => 'Manufacturer_List',
                'details'     => 'Add_Manufacturer',
                'type'        => 1,
            ],
            [
                'name'        => 'Edit_Manufacturer',
                'guard_name'  => 'web',
                'module_name' => 'Manufacturer_List',
                'details'     => 'Edit_Manufacturer',
                'type'        => 2,
            ],
            [
                'name'        => 'Status_Manufacturer',
                'guard_name'  => 'web',
                'module_name' => 'Manufacturer_List',
                'details'     => 'Status_Manufacturer',
                'type'        => 3,
            ],
            [
                'name'        => 'Delete_Manufacturer',
                'guard_name'  => 'web',
                'module_name' => 'Manufacturer_List',
                'details'     => 'Delete_Manufacturer',
                'type'        => 4,
            ],
            [
                'name'        => 'View_Manufacturer',
                'guard_name'  => 'web',
                'module_name' => 'Manufacturer_List',
                'details'     => 'View_Manufacturer',
                'type'        => 5,
            ],

            [
                'name'        => 'Add_Medicine',
                'guard_name'  => 'web',
                'module_name' => 'Medicine_List',
                'details'     => 'Add_Medicine',
                'type'        => 1,
            ],
            [
                'name'        => 'Edit_Medicine',
                'guard_name'  => 'web',
                'module_name' => 'Medicine_List',
                'details'     => 'Edit_Medicine',
                'type'        => 2,
            ],
            [
                'name'        => 'Status_Medicine',
                'guard_name'  => 'web',
                'module_name' => 'Medicine_List',
                'details'     => 'Status_Medicine',
                'type'        => 3,
            ],
            [
                'name'        => 'Delete_Medicine',
                'guard_name'  => 'web',
                'module_name' => 'Medicine_List',
                'details'     => 'Delete_Medicine',
                'type'        => 4,
            ],
            [
                'name'        => 'View_Medicine',
                'guard_name'  => 'web',
                'module_name' => 'Medicine_List',
                'details'     => 'View_Medicine',
                'type'        => 5,
            ],

            //Prescription
            [
                'name'        => 'Prescription',
                'guard_name'  => 'web',
                'module_name' => null,
                'details'     => 'MODULE',
                'type'        => null,
            ],
            [
                'name'        => 'Prescription_Add',
                'guard_name'  => 'web',
                'module_name' => 'Prescription',
                'details'     => 'FEATURE',
                'type'        => null,
            ],
            [
                'name'        => 'Prescription_List',
                'guard_name'  => 'web',
                'module_name' => 'Prescription',
                'details'     => 'FEATURE',
                'type'        => null,
            ],
            [
                'name'        => 'Add_Prescription',
                'guard_name'  => 'web',
                'module_name' => 'Prescription_List',
                'details'     => 'Add_Prescription',
                'type'        => 1,
            ],
            [
                'name'        => 'Edit_Prescription',
                'guard_name'  => 'web',
                'module_name' => 'Prescription_List',
                'details'     => 'Edit_Prescription',
                'type'        => 2,
            ],
            [
                'name'        => 'Status_Prescription',
                'guard_name'  => 'web',
                'module_name' => 'Prescription_List',
                'details'     => 'Status_Prescription',
                'type'        => 3,
            ],
            [
                'name'        => 'Delete_Prescription',
                'guard_name'  => 'web',
                'module_name' => 'Prescription_List',
                'details'     => 'Delete_Prescription',
                'type'        => 4,
            ],
            [
                'name'        => 'View_Prescription',
                'guard_name'  => 'web',
                'module_name' => 'Prescription_List',
                'details'     => 'View_Prescription',
                'type'        => 5,
            ],
            //Account
            [
                'name'        => 'Account',
                'guard_name'  => 'web',
                'module_name' => null,
                'details'     => 'MODULE',
                'type'        => null,
            ],
            [
                'name'        => 'Account_List',
                'guard_name'  => 'web',
                'module_name' => 'Account',
                'details'     => 'FEATURE',
                'type'        => null,
            ],
            [
                'name'        => 'Payment_List',
                'guard_name'  => 'web',
                'module_name' => 'Account',
                'details'     => 'FEATURE',
                'type'        => null,
            ],
            [
                'name'        => 'Account_Invoice_List',
                'guard_name'  => 'web',
                'module_name' => 'Account',
                'details'     => 'FEATURE',
                'type'        => null,
            ],
            [
                'name'        => 'Add_Account',
                'guard_name'  => 'web',
                'module_name' => 'Account',
                'details'     => 'Add_Account',
                'type'        => 1,
            ],
            [
                'name'        => 'Edit_Account',
                'guard_name'  => 'web',
                'module_name' => 'Account',
                'details'     => 'Edit_Account',
                'type'        => 2,
            ],
            [
                'name'        => 'Status_Account',
                'guard_name'  => 'web',
                'module_name' => 'Account',
                'details'     => 'Status_Account',
                'type'        => 3,
            ],
            [
                'name'        => 'Delete_Account',
                'guard_name'  => 'web',
                'module_name' => 'Account',
                'details'     => 'Delete_Account',
                'type'        => 4,
            ],
            [
                'name'        => 'View_Account',
                'guard_name'  => 'web',
                'module_name' => 'Account',
                'details'     => 'View_Account',
                'type'        => 5,
            ],
            [
                'name'        => 'Add_Payment',
                'guard_name'  => 'web',
                'module_name' => 'Account',
                'details'     => 'Add_Payment',
                'type'        => 1,
            ],
            [
                'name'        => 'Edit_Payment',
                'guard_name'  => 'web',
                'module_name' => 'Account',
                'details'     => 'Edit_Payment',
                'type'        => 2,
            ],
            [
                'name'        => 'Status_Payment',
                'guard_name'  => 'web',
                'module_name' => 'Account',
                'details'     => 'Status_Payment',
                'type'        => 3,
            ],
            [
                'name'        => 'Delete_Payment',
                'guard_name'  => 'web',
                'module_name' => 'Account',
                'details'     => 'Delete_Payment',
                'type'        => 4,
            ],
            [
                'name'        => 'View_Payment',
                'guard_name'  => 'web',
                'module_name' => 'Account',
                'details'     => 'View_Payment',
                'type'        => 5,
            ],

            [
                'name'        => 'Add_Account_Invoice',
                'guard_name'  => 'web',
                'module_name' => 'Account',
                'details'     => 'Add_Account_Invoice',
                'type'        => 1,
            ],
            [
                'name'        => 'Edit_Account_Invoice',
                'guard_name'  => 'web',
                'module_name' => 'Account',
                'details'     => 'Edit_Account_Invoice',
                'type'        => 2,
            ],
            [
                'name'        => 'Status_Account_Invoice',
                'guard_name'  => 'web',
                'module_name' => 'Account',
                'details'     => 'Status_Account_Invoice',
                'type'        => 3,
            ],
            [
                'name'        => 'Delete_Account_Invoice',
                'guard_name'  => 'web',
                'module_name' => 'Account',
                'details'     => 'Delete_Account_Invoice',
                'type'        => 4,
            ],
            [
                'name'        => 'View_Account_Invoice',
                'guard_name'  => 'web',
                'module_name' => 'Account',
                'details'     => 'View_Account_Invoice',
                'type'        => 5,
            ],

            //Human_Resource
            [
                'name'        => 'Human_Resource',
                'guard_name'  => 'web',
                'module_name' => null,
                'details'     => 'MODULE',
                'type'        => null,
            ],
            [
                'name'        => 'Employee_Type',
                'guard_name'  => 'web',
                'module_name' => 'Human_Resource',
                'details'     => 'FEATURE',
                'type'        => null,
            ],
            [
                'name'        => 'Employee_Add',
                'guard_name'  => 'web',
                'module_name' => 'Human_Resource',
                'details'     => 'FEATURE',
                'type'        => null,
            ],
            [
                'name'        => 'Employee_List',
                'guard_name'  => 'web',
                'module_name' => 'Human_Resource',
                'details'     => 'FEATURE',
                'type'        => null,
            ],
            [
                'name'        => 'Add_Employee_Type',
                'guard_name'  => 'web',
                'module_name' => 'Human_Resource',
                'details'     => 'Add_Employee_Type',
                'type'        => 1,
            ],
            [
                'name'        => 'Edit_Employee_Type',
                'guard_name'  => 'web',
                'module_name' => 'Human_Resource',
                'details'     => 'Edit_Employee_Type',
                'type'        => 2,
            ],
            [
                'name'        => 'Status_Employee_Type',
                'guard_name'  => 'web',
                'module_name' => 'Human_Resource',
                'details'     => 'Status_Employee_Type',
                'type'        => 3,
            ],
            [
                'name'        => 'Delete_Employee_Type',
                'guard_name'  => 'web',
                'module_name' => 'Human_Resource',
                'details'     => 'Delete_Employee_Type',
                'type'        => 4,
            ],
            [
                'name'        => 'View_Employee_Type',
                'guard_name'  => 'web',
                'module_name' => 'Human_Resource',
                'details'     => 'View_Employee_Type',
                'type'        => 5,
            ],
            [
                'name'        => 'Add_Employee',
                'guard_name'  => 'web',
                'module_name' => 'Human_Resource',
                'details'     => 'Add_Employee',
                'type'        => 1,
            ],
            [
                'name'        => 'Edit_Employee',
                'guard_name'  => 'web',
                'module_name' => 'Human_Resource',
                'details'     => 'Edit_Employee',
                'type'        => 2,
            ],
            [
                'name'        => 'Status_Employee',
                'guard_name'  => 'web',
                'module_name' => 'Human_Resource',
                'details'     => 'Status_Employee',
                'type'        => 3,
            ],
            [
                'name'        => 'Delete_Employee',
                'guard_name'  => 'web',
                'module_name' => 'Human_Resource',
                'details'     => 'Delete_Employee',
                'type'        => 4,
            ],
            [
                'name'        => 'View_Employee',
                'guard_name'  => 'web',
                'module_name' => 'Human_Resource',
                'details'     => 'View_Employee',
                'type'        => 5,
            ],
            //Settings
            [
                'name'        => 'Settings',
                'guard_name'  => 'web',
                'module_name' => null,
                'details'     => 'MODULE',
                'type'        => null,
            ],
            //Notice
            [
                'name'        => 'Notice',
                'guard_name'  => 'web',
                'module_name' => null,
                'details'     => 'MODULE',
                'type'        => null,
            ],
            [
                'name'        => 'Notice_Add',
                'guard_name'  => 'web',
                'module_name' => 'Notice',
                'details'     => 'FEATURE',
                'type'        => null,
            ],
            [
                'name'        => 'Notice_List',
                'guard_name'  => 'web',
                'module_name' => 'Notice',
                'details'     => 'FEATURE',
                'type'        => null,
            ],
            [
                'name'        => 'Add_Notice',
                'guard_name'  => 'web',
                'module_name' => 'Notice',
                'details'     => 'Add_Notice',
                'type'        => 1,
            ],
            [
                'name'        => 'Edit_Notice',
                'guard_name'  => 'web',
                'module_name' => 'Notice',
                'details'     => 'Edit_Notice',
                'type'        => 2,
            ],
            [
                'name'        => 'Status_Notice',
                'guard_name'  => 'web',
                'module_name' => 'Notice',
                'details'     => 'Status_Notice',
                'type'        => 3,
            ],
            [
                'name'        => 'Delete_Notice',
                'guard_name'  => 'web',
                'module_name' => 'Notice',
                'details'     => 'Delete_Notice',
                'type'        => 4,
            ],
            [
                'name'        => 'View_Notice',
                'guard_name'  => 'web',
                'module_name' => 'Notice',
                'details'     => 'View_Notice',
                'type'        => 5,
            ],
            //Mail
            [
                'name'        => 'Mail',
                'guard_name'  => 'web',
                'module_name' => null,
                'details'     => 'MODULE',
                'type'        => null,
            ],
            [
                'name'        => 'Add_Mail',
                'guard_name'  => 'web',
                'module_name' => 'Mail',
                'details'     => 'Add_Mail',
                'type'        => 1,
            ],
            [
                'name'        => 'Edit_Mail',
                'guard_name'  => 'web',
                'module_name' => 'Mail',
                'details'     => 'Edit_Mail',
                'type'        => 2,
            ],
            [
                'name'        => 'Status_Mail',
                'guard_name'  => 'web',
                'module_name' => 'Mail',
                'details'     => 'Status_Mail',
                'type'        => 3,
            ],
            [
                'name'        => 'Delete_Mail',
                'guard_name'  => 'web',
                'module_name' => 'Mail',
                'details'     => 'Delete_Mail',
                'type'        => 4,
            ],
            [
                'name'        => 'View_Mail',
                'guard_name'  => 'web',
                'module_name' => 'Mail',
                'details'     => 'View_Mail',
                'type'        => 5,
            ],
            //Billing
            [
                'name'        => 'Billing',
                'guard_name'  => 'web',
                'module_name' => null,
                'details'     => 'MODULE',
                'type'        => null,
            ],
            [
                'name'        => 'Service_Billing',
                'guard_name'  => 'web',
                'module_name' => 'Billing',
                'details'     => 'FEATURE',
                'type'        => null,
            ],
            [
                'name'        => 'Payment_Billing',
                'guard_name'  => 'web',
                'module_name' => 'Billing',
                'details'     => 'FEATURE',
                'type'        => null,
            ],
            [
                'name'        => 'Billing_Invoice',
                'guard_name'  => 'web',
                'module_name' => 'Billing',
                'details'     => 'FEATURE',
                'type'        => null,
            ],
            //Service_Billing
            [
                'name'        => 'Add_Service_Billing',
                'guard_name'  => 'web',
                'module_name' => 'Service_Billing',
                'details'     => 'Add_Service_Billing',
                'type'        => 1,
            ],
            [
                'name'        => 'Edit_Service_Billing',
                'guard_name'  => 'web',
                'module_name' => 'Service_Billing',
                'details'     => 'Edit_Service_Billing',
                'type'        => 2,
            ],
            [
                'name'        => 'Status_Service_Billing',
                'guard_name'  => 'web',
                'module_name' => 'Service_Billing',
                'details'     => 'Status_Service_Billing',
                'type'        => 3,
            ],
            [
                'name'        => 'Delete_Service_Billing',
                'guard_name'  => 'web',
                'module_name' => 'Service_Billing',
                'details'     => 'Delete_Service_Billing',
                'type'        => 4,
            ],
            [
                'name'        => 'View_Service_Billing',
                'guard_name'  => 'web',
                'module_name' => 'Service_Billing',
                'details'     => 'View_Service_Billing',
                'type'        => 5,
            ],
            //Payment_Billing
            [
                'name'        => 'Add_Payment_Billing',
                'guard_name'  => 'web',
                'module_name' => 'Payment_Billing',
                'details'     => 'Add_Payment_Billing',
                'type'        => 1,
            ],
            [
                'name'        => 'Edit_Payment_Billing',
                'guard_name'  => 'web',
                'module_name' => 'Payment_Billing',
                'details'     => 'Edit_Payment_Billing',
                'type'        => 2,
            ],
            [
                'name'        => 'Status_Payment_Billing',
                'guard_name'  => 'web',
                'module_name' => 'Payment_Billing',
                'details'     => 'Status_Payment_Billing',
                'type'        => 3,
            ],
            [
                'name'        => 'Delete_Payment_Billing',
                'guard_name'  => 'web',
                'module_name' => 'Payment_Billing',
                'details'     => 'Delete_Payment_Billing',
                'type'        => 4,
            ],
            [
                'name'        => 'View_Payment_Billing',
                'guard_name'  => 'web',
                'module_name' => 'Payment_Billing',
                'details'     => 'View_Payment_Billing',
                'type'        => 5,
            ],
            //Billing_Invoice
            [
                'name'        => 'Add_Billing_Invoice',
                'guard_name'  => 'web',
                'module_name' => 'Billing_Invoice',
                'details'     => 'Add_Billing_Invoice',
                'type'        => 1,
            ],
            [
                'name'        => 'Edit_Billing_Invoice',
                'guard_name'  => 'web',
                'module_name' => 'Billing_Invoice',
                'details'     => 'Edit_Billing_Invoice',
                'type'        => 2,
            ],
            [
                'name'        => 'Status_Billing_Invoice',
                'guard_name'  => 'web',
                'module_name' => 'Billing_Invoice',
                'details'     => 'Status_Billing_Invoice',
                'type'        => 3,
            ],
            [
                'name'        => 'Delete_Billing_Invoice',
                'guard_name'  => 'web',
                'module_name' => 'Billing_Invoice',
                'details'     => 'Delete_Billing_Invoice',
                'type'        => 4,
            ],
            [
                'name'        => 'View_Billing_Invoice',
                'guard_name'  => 'web',
                'module_name' => 'Billing_Invoice',
                'details'     => 'View_Billing_Invoice',
                'type'        => 5,
            ],

        ];
        ModelsPermission::insert($permissions);
    }
}
